language: android
dist: trusty
jdk: openjdk8
android:
  components:
    - build-tools-29.0.2
    - extra-android-m2repository
    - extra-google-m2repository
  licenses:
    - '.+'
before_install:
  - chmod +x gradlew
  - rm "${JAVA_HOME}/lib/security/cacerts"
  - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
  - yes | sdkmanager "platforms;android-30"
script:
  - ./gradlew check
  # cat MIDIDriver/build/outputs/lint-results.xml
  # - cd ./MIDIDriver && mvn install -DskipTests=true -Dandroid.sdk.path=$ANDROID_HOME
